const level1 = new Level(
    [new Enemy(),
    new Enemy(),
    new Enemy(),
    ], 

    [
    new Cloud(),
    ], 

    [
    new BackGroundObject('img/Background/Sky.png', 0, 0),
    new BackGroundObject('img/Background/Clouds.png', 0, 0),
    new BackGroundObject('img/Background/Mountain_Back.png', 0, 0),
    new BackGroundObject('img/Background/Mountain_Middle.png', 0, 0),
    new BackGroundObject('img/Background/Mountain_Front.png', 0, 0),
    new BackGroundObject('img/Background/Fuji.png', 0, 0),
    new BackGroundObject('img/Background/Shrine_Multiple.png', 0, 0),
    new BackGroundObject('img/Background/BackgroundTrees.png', 0, 0),
    new BackGroundObject('img/Background/Ground.png', 0, 0),
    new BackGroundObject('img/Background/Sky.png', 720, 0),
    new BackGroundObject('img/Background/Clouds.png', 720, 0),
    new BackGroundObject('img/Background/Mountain_Back.png', 720, 0),
    new BackGroundObject('img/Background/Mountain_Middle.png', 720, 0),
    new BackGroundObject('img/Background/Mountain_Front.png', 720, 0),
    new BackGroundObject('img/Background/BackgroundTrees.png', 720, 0),
    new BackGroundObject('img/Background/House.png', 720, 0),
    new BackGroundObject('img/Background/Ground.png', 720, 0),
    new BackGroundObject('img/Background/Sky.png', 720*2, 0),
    new BackGroundObject('img/Background/Clouds.png', 720*2, 0),
    new BackGroundObject('img/Background/Mountain_Back.png', 720*2, 0),
    new BackGroundObject('img/Background/Mountain_Middle.png', 720*2, 0),
    new BackGroundObject('img/Background/Mountain_Front.png', 720*2, 0),
    new BackGroundObject('img/Background/BackgroundTrees.png', 720*2, 0),
    new BackGroundObject('img/Background/Shrine_Single.png', 720*2, 0),
    new BackGroundObject('img/Background/Ground.png', 720*2, 0),
    new BackGroundObject('img/Background/Sky.png', 720*3, 0),
    new BackGroundObject('img/Background/Clouds.png', 720*3, 0),
    new BackGroundObject('img/Background/Mountain_Back.png', 720*3, 0),
    new BackGroundObject('img/Background/Mountain_Middle.png', 720*3, 0),
    new BackGroundObject('img/Background/Mountain_Front.png', 720*3, 0),
    new BackGroundObject('img/Background/BackgroundTrees.png', 720*3, 0),
    new BackGroundObject('img/Background/House.png', 720*3, 0),
    new BackGroundObject('img/Background/Ground.png', 720*3, 0),
    ]

);
